export const COMMAND_NAMES = [
  "8ball",
  "avatar",
  "ban",
  "banner",
  "boosters",
  "botinfo",
  "calc",
  "clear",
  "coinflip",
  "commandconfig",
  "dice",
  "help",
  "invite",
  "kick",
  "lock",
  "logs",
  "members",
  "meme",
  "nick",
  "ping",
  "poll",
  "purge",
  "report",
  "roles",
  "rps",
  "rules",
  "say",
  "serverinfo",
  "setadminrole",
  "setautorole",
  "setgoodbye",
  "setlanguage",
  "setlogs",
  "setmodrole",
  "setprefix",
  "setrules",
  "setwelcome",
  "ship",
  "slowmode",
  "stats",
  "status",
  "support",
  "timeout",
  "toggle",
  "translate",
  "unban",
  "unlock",
  "untimeout",
  "userinfo",
  "warn",
  "warnings"
] as const;

export type CommandName = (typeof COMMAND_NAMES)[number];

const commandNameSet = new Set(COMMAND_NAMES);

export function isCommandName(value: string): value is CommandName {
  return commandNameSet.has(value as CommandName);
}
